#!/bin/bash
#
# chkconfig:    345 83 04
# description: Kafka Connect is a distributed ETL system for Kafka
# processname: kafkaConnect
#
### BEGIN INIT INFO
# Provides: kafka
# Required-Start: $all
# Required-Stop: $all
# Short-Description: start and stop kafka connect process control system
# Description: Kafka Connect is a distributed ETL system for Kafka
### END INIT INFO

#/etc/init.d/kafka
DAEMON_PATH=/opt/kafka/bin
DAEMON_NAME=kafkaconnect
# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:$DAEMON_PATH

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        pid=`ps ax | grep -i 'kafka.connect' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
            echo "Kafka Connect is already running"
        else
          echo "Starting $DAEMON_NAME"
          $DAEMON_PATH/connect-distributed.sh -daemon /opt/kafka/config/worker.properties
        fi
        ;;
  stop)
        echo "Shutting down $DAEMON_NAME"
        $DAEMON_PATH/kafka-connect-stop.sh
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i 'kafka.connect' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "Kafka Connect is Running as PID: $pid"
        else
          echo "Kafka Connect is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
